[pytest]
addopts = -p no:playwright
          # 禁用playwright插件，避免与本地的冲突
          --headed
          --tracing=retain-on-failure
          --screenshot=only-on-failure
          --video=retain-on-failure
          --base-url=https://pmms01-test.runjian.com/
          # 禁用pytest的日志记录功能，避免与自定义日志重复
          --capture=no

# 已独立配置日志记录器，以下是日志相关的配置项，可以根据需要启用
; log_cli = true
; log_cli_level = INFO  # 默认日志级别为debug，可以根据需要调整为DEBUG、WARNING等